### ISSUE TITLE
on icon-button add support for more events other than @click

### ISSUE THREAD

**Issue by wiffbi** [rashfael/buntpapier#18]
At pretix we are using your wonderful bunt-icon-button. A feature we are working on requires us to bind to @pointerdown/pointerup-events. Currently bunt-icon-button seems to only support @click. 

This works:

`bunt-icon-button(@click ="decPointerDown") minus`

This does not work/does not bind to the pointerdown-event on the HTML-Element:

`bunt-icon-button(@pointerdown="decPointerDown") minus`

Would it be possible to transparently bind events, that bunt-icon-button itself does not know about? 

Our workaround is to bind the pointer-events to the containing HTML-Element. It works, but looks unnecessarily _ugly_ to me.

**Comment by rashfael** [comment]
The best solution would be to use `$listeners` https://vuejs.org/v2/api/#vm-listeners (which did not exist back when buntpapier started out) on the buntpapier side.

What I have been doing in my projects instead is to use `.native`:

```
bunt-icon-button(@pointerdown.native="decPointerDown") minus
```

Do you mean that by `bind the pointer-events to the containing HTML-Element` ?

**Comment by wiffbi** [comment]
Ah, `.native` it is! Thank you for your super quick reply!

Regarding binding the pointer-events to the containing HTML-element, I meant that I created a div/span around the `bunt-icon-button` and attached the Eventlisteners there. But `.native` is the solution. Thanks again so much!
